# Generated by Django 3.0.2 on 2020-05-31 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_title', models.CharField(blank=True, max_length=500, null=True)),
                ('folder_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=250)),
                ('document_file', models.FileField(default='', upload_to='')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentFolder')),
            ],
        ),
    ]
