# Generated by Django 2.2b1 on 2019-03-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250)),
                ('image_file', models.FileField(default='', upload_to='')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.ImageFolder')),
            ],
        ),
    ]
