# Generated by Django 2.2b1 on 2019-04-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RemoveField(
            model_name='table',
            name='code',
        ),
        migrations.RemoveField(
            model_name='table',
            name='created',
        ),
        migrations.RemoveField(
            model_name='table',
            name='language',
        ),
        migrations.RemoveField(
            model_name='table',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='table',
            name='style',
        ),
        migrations.AddField(
            model_name='table',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Table'),
        ),
    ]
