# Generated by Django 2.2b1 on 2019-04-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20190416_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
