# Generated by Django 2.2b1 on 2019-04-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_values_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('parameter_title',)},
        ),
    ]
