# Generated by Django 2.2b1 on 2019-04-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20190417_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='parameter_name',
        ),
        migrations.AddField(
            model_name='values',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.Parameter'),
        ),
        migrations.AlterField(
            model_name='values',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
