# Generated by Django 2.2b1 on 2019-04-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20190417_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.Parameter'),
        ),
    ]
