# Generated by Django 2.2b1 on 2019-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_parameter_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
